resolver: lts-9.10

packages:
- '.'

extra-deps: []

flags:
  snap-server:
    openssl: True
  
  HsOpenSSL:
    extra-include-dirs:
    - /usr/local/opt/openssl/include
    extra-lib-dirs:
    - /usr/local/opt/openssl/lib

extra-package-dbs: []
